# Generated by Django 5.0.3 on 2024-03-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gadgetapp", "0002_alter_gadget_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gadget",
            name="category",
            field=models.CharField(
                choices=[
                    ("laptops", "Laptops"),
                    ("desktops", "Desktops"),
                    ("television", "Television"),
                    ("mobiles", "Mobiles"),
                    ("tablets", "Tablets"),
                    ("ipads", "Ipads"),
                    ("printers", "Printers"),
                    ("camera", "Camera"),
                    ("headphones", "Headphones"),
                ],
                max_length=10,
            ),
        ),
    ]
