# Generated by Django 5.0.3 on 2024-04-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gadgetapp", "0005_alter_gadget_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
