# Generated by Django 5.0.3 on 2024-04-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gadgetapp", "0006_newsletter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profileuser",
            name="role",
            field=models.CharField(
                choices=[("owner", "Owner"), ("user", "User")], max_length=10
            ),
        ),
    ]
